version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: language-toolkit
    restart: unless-stopped
    ports:
      - "${PORT:-8000}:8000"
    volumes:
      - ./logs:/app/logs
      - ./temp:/app/temp
      - ./uploads:/app/uploads
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3