version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: language-toolkit-api
    restart: always
    expose:
      - "8000"
    volumes:
      - ./logs:/app/logs
      - ./temp:/app/temp
      - ./uploads:/app/uploads
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: language-toolkit-nginx
    restart: always
    ports:
      - "8080:80"    # Changed from 80:80 to avoid conflicts
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  logs:
  temp:
  uploads: